baseURL = "/"
languageCode = "en-us"
title = "MVPS"

[[menu.main]]
  name = "Food"
  weight = -70
  url = "categories/food"

[[menu.main]]
  name = "About"
  weight = -70
  url = "/about"

[[menu.main]]
  name = "Drinks"
  weight = -70
  url = "categories/drinks"

[params]
  description = "MVPS, gril and patio"
  author = "github.com/colorlessenergy"
